### ISSUE TITLE
Improve CLI UX

### ISSUE THREAD

**Issue by jeffmendoza** [guacsec/guac#719]
How to run the various GUAC pieces is a bit haphazard eg which binary and which subcommand to use.

I propose a rename/shuffle of the commands. Overall the theory is to divide the commands into two categories:

- User-facing: Made to be run by a user / tester to accomplish something. Should be consistent and intuitive CLI UX. One powerful command makes sense for the user to learn.
- Service: Things to be run as a service, ex: in a container, as a cron, as a systemd service, etc. Seperate single-purpose binaries make sense.

Also, the main server is the same between demo and "real" deployments, so just have one way to run that.

**server**:
- name: **guacgql**
- what it does: runs a GraphQL server
- options:
  - backend: inmem or neo4j or future DB
  - backend-specific options: neo4j connection options
  - playground / debug: also start playground
 
**all-in-one (user facing):**
- name: **guacone**
- what it does: performs user-facing operations that require setting up a processor / ingestor / assembler in one binary, only talks to GQL, no nats/csub
- options:
  - gql endpoint
- commands:
  - certify \<type\> - runs the \<type\> certifier once (once by default, optional poll)
  - collector \<type\> - runs the \<type\> collector once, includes "files" (once by default, optional poll)
  - query \<name\> -  runs the canned \<name\>  query.

**services:**

- name: **guaccsub**
- what it does: runs the collector-subscriber service
- options:
  - listening port

- name: **guacingest**
- what it does: runs the ingestor connected to nats and GraphQL
- options:
  - nats addr
  - gql endpoint

- name: **guaccollect**
- what it does: runs the named collector or certifier connected to GraphQL and nats
- options:
  - nats addr
  - gql addr
  - colsub addr
  - collector/certifier name
  - polling options
 
**Other notes:**

Prefix all the binaries with `guac`. Binaries could eventually be installed in `/usr/bin`. Avoid collisions by namespacing, `ingestor` or `collector` are too generic.

**Todo**

From where we are now, I think this is all that is needed.

- [x] Merge `graphql_playground` and `guacone gql-server` to a single `guacgql` command. (I have this done already, will open PR).
- [x] Rename `ingest` to `guacingest`.
- [x] Rename `collector` to `guaccollect`
- [x] Move `guacone csub-server` to `guaccsub`
- [x] Rework the collectors / certifiers in guacone to be subcommands, ex: `certifier <name>` and change to default to once-only

I believe the certifiers in `guacone` all use the all-in-one "processor / ingestor / assembler" currently, so those stay as is. Later we can add certifiers to the `guaccollect` command that uses the nats ingestion pipeline and is meant for the service usecase.

Please share opinions and correct me where I'm mistaken. I'm trying to grasp what all the pieces do.

**Comment by pxp928** [comment]
This makes sense. 

> collector <type> - runs the <type> collector once (once by default, optional poll)
files - ingests the files (once)

The files should be part of the collector (as a subtype) as the files is a collector.

> what it does: runs the collector-subscriber connected to nats?

Collector subscriber does not use NATS. It has its own in-memory DB that it pulls from.

**Comment by mlieberman85** [comment]
This makes sense to me.

I also think we should probably add query use cases with some canned queries. I'm trying to think about what folks would want to start doing with GUAC right now if they had ingested some SBOMs. They would probably want a simple command to query for known vulns (I know we just added that) along with similar ones. e.g. do I have an SBOM for a particular artifact. Do I have info about a hash, etc.

**Comment by jeffmendoza** [comment]
I've updated the first post, PTAL.

> The files should be part of the collector (as a subtype) as the files is a collector.

Done, `guacone`:  "collector <type> - runs the <type> collector once, includes "files" (once by default, optional poll)"

> Collector subscriber does not use NATS. It has its own in-memory DB that it pulls from.

Updated description.

> I also think we should probably add query use cases with some canned queries.

Good point, added that to `guacone`

> isn't this already in the --debug flag?

Yep, it is there in `guacone gql-server`, so just merging that with the `graphql_playground` command and moving to own `guac` command.

> I would say that one aspect of this is to keep the viper config stuff, i think that that's very convenient which lets you have 1 config file across all the deployments.

Agree, no change there.

> I'd say guaccol -> guaccollect just for clarity

SG, updated.

> and i think guaccert should be under guaccollect since i believe the certifiers may eventually move to work through the collectsub service.

Agree, updated.

> The collectsub service is also missing from the list i believe

It is the first one under services `guaccsub`.

**Comment by jeffmendoza** [comment]
So the worry is that if we name the server `guac`, folks would think that guac is just the server, and we wan to make it clear that the whole set of services is GUAC, and the server is just one piece?

**Comment by pxp928** [comment]
Yes, that is correct.

**Comment by jeffmendoza** [comment]
Proposal updated

**Comment by jeffmendoza** [comment]
One thing I don't have are toy / example / dev commands. ex: https://github.com/guacsec/guac/blob/main/cmd/collector/cmd/example.go
https://github.com/guacsec/guac/blob/main/cmd/guacone/cmd/collectsub_client.go

Maybe we should have a **guacdev** command for that?

**Comment by lumjjb** [comment]
I think csub client is still something that is user facing (@mlieberman85 and i chatted about this around the use case of someone wanting to know what are the list of things their organization is tracking in this GUAC instance).

For example collector i am fine with removing that or temporary moving the example collector files into internal test for later use.

**Comment by jeffmendoza** [comment]
Sounds good, I leave `csub-client` as a part of `guacone`, and move the examples and `pubsub_test` under `internal/testing/cmd`

**Comment by jeffmendoza** [comment]
Closing this as done, I'll open a new one for future needs.
